const GET_INFO_REQ = 'GET_INFO_USER_REQ';
const GET_INFO_FAIL = 'GET_INFO_USER_FAIL';
const GET_INFO_USER_SUC = 'GET_INFO_USER_SUC';
const GET_INFO_REPO_SUC = 'GET_INFO_REPO_SUC';
const CLEAN_RESULTS = 'CLEAN_RESULTS';
const SET_SEARCH = 'SET_SEARCH';

export {
    GET_INFO_REQ,
    GET_INFO_FAIL,
    GET_INFO_USER_SUC,
    GET_INFO_REPO_SUC,
    CLEAN_RESULTS,
    SET_SEARCH,
}
